# Generated by Django 4.0.4 on 2024-05-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_doctordetails_password_doctordetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
