# Generated by Django 4.0.4 on 2024-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userregister',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
